Testsuite overhaul
* testsuite/defs: Support VERBOSE=1 - echoing which test it runs, and a
  description - and VERBOSE=* - the old behaviour.
* testsuite/do-test: Check for the ${testname}.in file in both the
  objdir, and the sourcedir.
* testsuite/exim.in: Removed.
* testsuite/exim.ok: Likewise.
* testsuite/apm.in: Likewise.
* testsuite/apm.ok: Likewise.
* testsuite/color.test: Likewise.
* testsuite/bug-wnum.test: New test, extracted from the former
  color.test.
* testsuite/bug-procmailsubj.test: Likewise.
* testsuite/procmail.in: Renamed to...
* testsuite/bug-procmailsubj.in: ...this.
* testsuite/procmail.ok: Renamed to...
* testsuite/bug-procmailsubj.ok: ...this.
* testsuite/bug-wnum.test: New test, extracted from the former
  color.test.
* testsuite/bug-sysrepeat.test: Likewise.
* testsuite/syslog.in: Renamed to...
* testsuite/bug-sysrepeat.in: ...this.
* testsuite/syslog.ok: Renamed to...
* testsuite/bug-sysrepeat.ok: ...this.
* testsuite/Makefile.in (TESTS): Updated according to the above
  changes.
  (TEST_IO): New variable.
  (EXTRA_DIST): Compute dynamically using ${TEST_IO}.
* testsuite/version.test: Added DESCRIPTION.

git-archimport-id: algernon@bonehunter.rulez.org--iluvatar-archive/ccze--0.1--patch-225

diff --git a/testsuite/defs b/testsuite/defs
--- a/testsuite/defs
+++ b/testsuite/defs
@@ -22,31 +22,45 @@
 PACKAGE=${PACKAGE-ccze}
 
 srcdir=${srcdir-.}
-if test ! -d $srcdir ; then
-    echo "defs: installation error" 1>&2
-    exit 1
+if test ! -d ${srcdir}; then
+	echo "defs: installation error" 1>&2
+	exit 1
 fi
 
-srcdir=`\cd $srcdir && pwd`
+srcdir=`\cd ${srcdir} && pwd`
 top_builddir=`\cd ${top_builddir-..} && pwd`
 
 progname=`echo "$0" | sed 's,^.*/,,'`
-testname=`echo "$progname" | sed 's,\.test$,,'`
+testname=`echo "${progname}" | sed 's,\.test$,,'`
 testsubdir=${testsubdir-test-tmp}
 
 # User can set VERBOSE to prevent output redirection
-case x$VERBOSE in
-    xNO | xno | x0 | x)
-        exec > /dev/null 2>&1
-        ;;
+TEST_DESC=""
+case x${VERBOSE} in
+	xNO|xno|x0|x)
+		exec 2>/dev/null
+		exec 3>/dev/null
+		;;
+	x1)
+		exec 2>/dev/null
+		exec 3>&1
+		TEST_DESC="${DESCRIPTION}"
+		;;
+	*)
+		TEST_DESC="${DESCRIPTION}"
+		exec 3>&1
+		;;
 esac
 
-rm -rf $testsubdir > /dev/null 2>&1
-mkdir $testsubdir
-cd $testsubdir \
-   || { echo "Cannot make or change into $testsubdir"; exit 1; }
+rm -rf ${testsubdir} >/dev/null 2>&1
+mkdir ${testsubdir}
+cd ${testsubdir} \
+   || { echo "Cannot make or change into ${testsubdir}"; exit 1; }
 
-echo "=== Running test $testname"
+echo "=== Running test ${testname}" >&3
+if ! test -z "${TEST_DESC}"; then
+	echo "=== ${TEST_DESC}" >&3
+fi
 
 CMP="${CMP-cmp}"
-RUNPROG="${top_builddir}/src/$PACKAGE"
+RUNPROG="${top_builddir}/src/${PACKAGE}"
